### ISSUE TITLE
Escape Hatch for missing properties?

### ISSUE THREAD

**Issue by born2defy** [nsaunders/purescript-tecton#28]
### Problem
There are a few missing properties (such as userSelect), and there is no easy way to add these without forking the library due to orphan instances.  

### Requested enhancement
Is it possible to include an escape hatch to inline a property declaration as a string just to not have to avoid an entire declaration for one missing prop?  

### Anything else?
Provide any additional context or details you think might be helpful.

**Comment by nsaunders** [comment]
Hi @born2defy, thanks for your interest in Tecton. Yes, I would say that the "escape hatch" has been in the back of my mind, but it's good to have this issue as a reminder, so thanks for submitting.

That said, I would generally prefer to add missing properties. Were you specifically interested in `userSelect`, or was that just an example? If so, we should be able to get that property added pretty quickly, as (fortunately) the scope seems pretty small ([spec](https://www.w3.org/TR/css-ui-4/#propdef-user-select)).

**Comment by nsaunders** [comment]
Resolved in #40
