### ISSUE TITLE
Support multiple class-name requirements

### ISSUE THREAD

**Issue by silky** [nsaunders/purescript-tecton#43]
I think it's valid CSS to have something like:

```
a.x.y { color: red; }
```

where it only matches

```
<a class="x y">...
```

But the only way to do this here is to "hack" the class name, like so:

```
a &. ClassName "x.y" ? Rule.do color := red
```

I was hoping something like:

```
a &. (ClassName "x"  /\ ClassName "y") ...
```

or

```
a &. (ClassName "x"  <> ClassName "y") ...
```

might work? thoughts? am i missing the right way to do this?

**Comment by nsaunders** [comment]
Hi @silky, here's how to append multiple class names to a selector:

```haskell
a &. ClassName "x" &. ClassName "y" ? Rule.do
  color := rgb 255 0 0
```

Result:

```css
a.x.y {
  color: hsl(0.0, 100.0%, 50.0%);
}
```

**Comment by silky** [comment]
ah i see; thanks @nsaunders ! :)

**Comment by nsaunders** [comment]
Certainly, please let me know if you need anything else!
