### ISSUE TITLE
Property order

### ISSUE THREAD

**Issue by toastal** [nsaunders/purescript-tecton#5]
### Problem
Can you output properties in a different order? Alphabetical is like the least useful order to read properties as a consumer--even if it's a consistent system to order things.

### Requested enhancement
Something along the lines of https://github.com/constverum/stylelint-config-rational-order

### References
n/a

### Anything else?
nope

**Comment by nsaunders** [comment]
For what it's worth, I think I've found a solution to the declaration ordering issue (i.e. declarations potentially not rendered in input order). Depending on the results of my testing/benchmarking, I may publish an update soon.

Unfortunately, as I'm sure you've already realized, that doesn't eliminate the need for a tool like CSScomb if you actually _do_ want the output to be reordered.
